[2023-07-13 22:40:15,855] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:40:15.121132+00:00 [queued]>
[2023-07-13 22:40:15,863] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:40:15.121132+00:00 [queued]>
[2023-07-13 22:40:15,864] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:40:15,864] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2023-07-13 22:40:15,865] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:40:15,877] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): execute_python_script> on 2023-07-13 22:40:15.121132+00:00
[2023-07-13 22:40:15,880] {standard_task_runner.py:52} INFO - Started process 253 to run task
[2023-07-13 22:40:15,882] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'execute_python_script', 'manual__2023-07-13T22:40:15.121132+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpn_7snyxr', '--error-file', '/tmp/tmpxeayggx8']
[2023-07-13 22:40:15,884] {standard_task_runner.py:80} INFO - Job 34: Subtask execute_python_script
[2023-07-13 22:40:15,930] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:40:15.121132+00:00 [running]> on host a917c5d777dc
[2023-07-13 22:40:15,975] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fvinciguerra
AIRFLOW_CTX_DAG_ID=ETL_stock_data_google_DAG
AIRFLOW_CTX_TASK_ID=execute_python_script
AIRFLOW_CTX_EXECUTION_DATE=2023-07-13T22:40:15.121132+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-13T22:40:15.121132+00:00
[2023-07-13 22:40:15,977] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 22:40:15,978] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/pyscripts\\ETL_stock_data_google.py']
[2023-07-13 22:40:15,984] {subprocess.py:85} INFO - Output:
[2023-07-13 22:40:16,057] {subprocess.py:89} INFO - python: can't open file '/opt/***/dags/pyscriptsETL_stock_data_google.py': [Errno 2] No such file or directory
[2023-07-13 22:40:16,060] {subprocess.py:93} INFO - Command exited with return code 2
[2023-07-13 22:40:16,070] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-13 22:40:16,075] {taskinstance.py:1278} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=execute_python_script, execution_date=20230713T224015, start_date=20230713T224015, end_date=20230713T224016
[2023-07-13 22:40:16,088] {standard_task_runner.py:93} ERROR - Failed to execute job 34 for task execute_python_script (Bash command failed. The command returned a non-zero exit code 2.; 253)
[2023-07-13 22:40:16,096] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-13 22:40:16,121] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
