[2023-07-19T21:12:45.721+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:11:38.672382+00:00 [queued]>
[2023-07-19T21:12:45.907+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:11:38.672382+00:00 [queued]>
[2023-07-19T21:12:45.908+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-19T21:12:45.928+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_completion_email> on 2023-07-19 21:11:38.672382+00:00
[2023-07-19T21:12:45.933+0000] {standard_task_runner.py:57} INFO - Started process 253 to run task
[2023-07-19T21:12:45.937+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'send_completion_email', 'manual__2023-07-19T21:11:38.672382+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpssbqmx9z']
[2023-07-19T21:12:45.941+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask send_completion_email
[2023-07-19T21:12:45.999+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:11:38.672382+00:00 [running]> on host 90317fb99301
[2023-07-19T21:12:46.113+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fvinciguerra' AIRFLOW_CTX_DAG_ID='ETL_stock_data_google_DAG' AIRFLOW_CTX_TASK_ID='send_completion_email' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T21:11:38.672382+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-19T21:11:38.672382+00:00'
[2023-07-19T21:12:46.130+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_stock_data_google_DAG.py", line 38, in send_completion_email
    server.connect(smtp_config.get("smtp_host"), smtp_config.get("smtp_port"))
  File "/usr/local/lib/python3.8/smtplib.py", line 328, in connect
    if not port and (host.find(':') == host.rfind(':')):
AttributeError: 'NoneType' object has no attribute 'find'
[2023-07-19T21:12:46.156+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=send_completion_email, execution_date=20230719T211138, start_date=20230719T211245, end_date=20230719T211246
[2023-07-19T21:12:46.192+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task send_completion_email ('NoneType' object has no attribute 'find'; 253)
[2023-07-19T21:12:46.207+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-19T21:12:46.228+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
