[2023-07-19T21:03:50.102+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:02:45.147385+00:00 [queued]>
[2023-07-19T21:03:50.217+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:02:45.147385+00:00 [queued]>
[2023-07-19T21:03:50.218+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-19T21:03:50.236+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): send_completion_email> on 2023-07-19 21:02:45.147385+00:00
[2023-07-19T21:03:50.241+0000] {standard_task_runner.py:57} INFO - Started process 233 to run task
[2023-07-19T21:03:50.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'send_completion_email', 'manual__2023-07-19T21:02:45.147385+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpt02by7o1']
[2023-07-19T21:03:50.248+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask send_completion_email
[2023-07-19T21:03:50.303+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.send_completion_email manual__2023-07-19T21:02:45.147385+00:00 [running]> on host 90317fb99301
[2023-07-19T21:03:50.390+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fvinciguerra' AIRFLOW_CTX_DAG_ID='ETL_stock_data_google_DAG' AIRFLOW_CTX_TASK_ID='send_completion_email' AIRFLOW_CTX_EXECUTION_DATE='2023-07-19T21:02:45.147385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-19T21:02:45.147385+00:00'
[2023-07-19T21:03:50.405+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_stock_data_google_DAG.py", line 38, in send_completion_email
    server.ehlo()
  File "/usr/local/lib/python3.8/smtplib.py", line 449, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/local/lib/python3.8/smtplib.py", line 376, in putcmd
    self.send(f'{s}{CRLF}')
  File "/usr/local/lib/python3.8/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
[2023-07-19T21:03:50.428+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=send_completion_email, execution_date=20230719T210245, start_date=20230719T210350, end_date=20230719T210350
[2023-07-19T21:03:50.443+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task send_completion_email (please run connect() first; 233)
[2023-07-19T21:03:50.491+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-19T21:03:50.509+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
