[2023-07-13 22:31:01,404] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:31:00.395560+00:00 [queued]>
[2023-07-13 22:31:01,412] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:31:00.395560+00:00 [queued]>
[2023-07-13 22:31:01,413] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:31:01,414] {taskinstance.py:1250} INFO - Starting attempt 1 of 1
[2023-07-13 22:31:01,415] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2023-07-13 22:31:01,427] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): execute_python_script> on 2023-07-13 22:31:00.395560+00:00
[2023-07-13 22:31:01,429] {standard_task_runner.py:52} INFO - Started process 244 to run task
[2023-07-13 22:31:01,432] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'execute_python_script', 'manual__2023-07-13T22:31:00.395560+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmpofejuhl5', '--error-file', '/tmp/tmpegd_lvy_']
[2023-07-13 22:31:01,434] {standard_task_runner.py:80} INFO - Job 31: Subtask execute_python_script
[2023-07-13 22:31:01,482] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.execute_python_script manual__2023-07-13T22:31:00.395560+00:00 [running]> on host a917c5d777dc
[2023-07-13 22:31:01,528] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=fvinciguerra
AIRFLOW_CTX_DAG_ID=ETL_stock_data_google_DAG
AIRFLOW_CTX_TASK_ID=execute_python_script
AIRFLOW_CTX_EXECUTION_DATE=2023-07-13T22:31:00.395560+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-13T22:31:00.395560+00:00
[2023-07-13 22:31:01,529] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-07-13 22:31:01,531] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python pyscripts.ETL_stock_data_google.py']
[2023-07-13 22:31:01,535] {subprocess.py:85} INFO - Output:
[2023-07-13 22:31:01,605] {subprocess.py:89} INFO - python: can't open file 'pyscripts.ETL_stock_data_google.py': [Errno 2] No such file or directory
[2023-07-13 22:31:01,607] {subprocess.py:93} INFO - Command exited with return code 2
[2023-07-13 22:31:01,617] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-13 22:31:01,622] {taskinstance.py:1278} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=execute_python_script, execution_date=20230713T223100, start_date=20230713T223101, end_date=20230713T223101
[2023-07-13 22:31:01,635] {standard_task_runner.py:93} ERROR - Failed to execute job 31 for task execute_python_script (Bash command failed. The command returned a non-zero exit code 2.; 244)
[2023-07-13 22:31:01,646] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-13 22:31:01,668] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
