[2023-07-20T14:44:37.741+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_alerta manual__2023-07-20T14:43:22.730926+00:00 [queued]>
[2023-07-20T14:44:37.921+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_alerta manual__2023-07-20T14:43:22.730926+00:00 [queued]>
[2023-07-20T14:44:37.923+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-20T14:44:37.959+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dag_envio_alerta> on 2023-07-20 14:43:22.730926+00:00
[2023-07-20T14:44:37.972+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2023-07-20T14:44:37.983+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'dag_envio_alerta', 'manual__2023-07-20T14:43:22.730926+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmp5l6_q6h7']
[2023-07-20T14:44:37.991+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask dag_envio_alerta
[2023-07-20T14:44:38.080+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.dag_envio_alerta manual__2023-07-20T14:43:22.730926+00:00 [running]> on host 90317fb99301
[2023-07-20T14:44:38.231+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fvinciguerra' AIRFLOW_CTX_DAG_ID='ETL_stock_data_google_DAG' AIRFLOW_CTX_TASK_ID='dag_envio_alerta' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T14:43:22.730926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-20T14:43:22.730926+00:00'
[2023-07-20T14:44:38.234+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-20T14:44:38.236+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python pyscripts/Alert_monthvalues_stock_data_google.py']
[2023-07-20T14:44:38.250+0000] {subprocess.py:86} INFO - Output:
[2023-07-20T14:44:38.372+0000] {subprocess.py:93} INFO - python: can't open file 'pyscripts/Alert_monthvalues_stock_data_google.py': [Errno 2] No such file or directory
[2023-07-20T14:44:38.375+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-20T14:44:38.391+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-20T14:44:38.399+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ETL_stock_data_google_DAG, task_id=dag_envio_alerta, execution_date=20230720T144322, start_date=20230720T144437, end_date=20230720T144438
[2023-07-20T14:44:38.425+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task dag_envio_alerta (Bash command failed. The command returned a non-zero exit code 2.; 270)
[2023-07-20T14:44:38.442+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-20T14:44:38.484+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
