[2023-07-20T15:00:16.659+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T15:00:08.735364+00:00 [queued]>
[2023-07-20T15:00:16.786+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T15:00:08.735364+00:00 [queued]>
[2023-07-20T15:00:16.789+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-20T15:00:16.807+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): dag_envio_error> on 2023-07-20 15:00:08.735364+00:00
[2023-07-20T15:00:16.811+0000] {standard_task_runner.py:57} INFO - Started process 263 to run task
[2023-07-20T15:00:16.814+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_stock_data_google_DAG', 'dag_envio_error', 'manual__2023-07-20T15:00:08.735364+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/ETL_stock_data_google_DAG.py', '--cfg-path', '/tmp/tmp49h__sof']
[2023-07-20T15:00:16.817+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask dag_envio_error
[2023-07-20T15:00:16.868+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_stock_data_google_DAG.dag_envio_error manual__2023-07-20T15:00:08.735364+00:00 [running]> on host 90317fb99301
[2023-07-20T15:00:16.944+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fvinciguerra' AIRFLOW_CTX_DAG_ID='ETL_stock_data_google_DAG' AIRFLOW_CTX_TASK_ID='dag_envio_error' AIRFLOW_CTX_EXECUTION_DATE='2023-07-20T15:00:08.735364+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-20T15:00:08.735364+00:00'
[2023-07-20T15:00:19.170+0000] {logging_mixin.py:149} INFO - Exito al enviar el mail
[2023-07-20T15:00:19.171+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-07-20T15:00:19.180+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=ETL_stock_data_google_DAG, task_id=dag_envio_error, execution_date=20230720T150008, start_date=20230720T150016, end_date=20230720T150019
[2023-07-20T15:00:19.242+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-20T15:00:19.259+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
